frase = 'Curso em Vídeo Python'
frase2 = '   Aprenda Python  '
frase3 = frase.split()
print(frase)
print(frase.lower())
print(frase.upper())
print(frase.capitalize())
print(frase.title())
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(frase.split())
print('-'.join(frase3))
print(frase[:5])
print(frase[6:8])
print(frase[9:14])
print(frase[15:])
print(frase[::2])
print(frase[9::3])
print(len(frase))
print(frase.count('o',0,14))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso'in frase)
print(frase.replace('Python', 'Android'))

