<Box>:
    orientation: 'vertical'
    BoxLayout:
        Label: 
            text: 'User'
            font_size: 50
        TextInput:
            font_size: 50
            text_align: 'center'
    BoxLayout:
        Label:
            text:'Password'
            font_size: 50
        TextInput:
            password: True
            font_size: 50
    BoxLayout:
        Button:
            text:'Enviar'
        Button:
            text:'Cancelar'
        
