nome = input('Qual é seu nome? ').strip()
print('Analisando seu nome...')
print('Seu nome em MAIÚSCULAS é: {}.'.format(nome.upper()))
print('Seu nome em minúsculas é: {}.'.format(nome.lower()))
print('Seu nome tem {} letras!'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras!'.format(separa[0], len(separa[0])))
